name: React App Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run:  |
        npm install
        npm run build
      env:
          REACT_APP_MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
    - name: Deploy
      uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
